# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
  default: arbitrum-yearn-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - yearn/yearn-vaults@0.4.6
  - OpenZeppelin/openzeppelin-contracts@4.7.1

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version:
    remappings:
      - "@yearnvaults=yearn/yearn-vaults@0.4.6"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.1"

reports:
  exclude_contracts:
    - Math
    - Vault
    - Ownable
    - Address
    - BaseStrategy
    - SafeERC20